/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualbiblioteca;

import Models.Autor;
import Models.Libro;
import Models.Nautor;
import Models.Nlibro;
import static biblioteca_departamental.Biblioteca_departamental.bib;
import javax.swing.JOptionPane;
import static visualbiblioteca.Second.isNumeric;

/**
 *
 * @author Estudiantes
 */
public class Five extends javax.swing.JFrame {

    /**
     * Creates new form Five
     */
    public Five() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //survive willi!
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        au = new javax.swing.JTextField();
        libro = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Autor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Libro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Genero");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        getContentPane().add(au, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));
        getContentPane().add(libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, -1));
        getContentPane().add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        jLabel5.setText("ISBN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconandImagen/12009316-Pila-de-libros-en-una-cubierta-de-color-naranja-sobre-fondo-gris-Foto-de-archivo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FirstView Vista = new FirstView();
        Vista.setVisible(true);
        Vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (isNumeric(au.getText()) || au.getText().equals("") || gen.getText().equals("") || libro.getText().equals("") || cod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error el nombre no puede contener numeros o  ningun campo puede estar vacio");
        } else {
            Nlibro ntemp = bib.getLibrosI();//nodo inicial de libros
            Libro ltemp = new Libro(libro.getText(), cod.getText(), gen.getText());//libro temporal
            while (ntemp != null) {//isbn del libro;
                if (ntemp.equals(new Nlibro(ltemp))) {
                    JOptionPane.showMessageDialog(null,"El ISBN ya se ha utilizado");
                    break;
                }
                ntemp = ntemp.getRl();
            }
            if (ntemp == null) {//si el isbn no esta siendo utilizado
                Nautor autemp = bib.getAutoresI();
                while (autemp != null) {//Buscar autor 
                    if (autemp.equals(new Nautor(new Autor(au.getText())))) {
                        break;
                    }
                    autemp = autemp.getRl();
                }
                if (autemp == null) {
                    autemp = new Nautor(new Autor(au.getText()));
                    if (bib.getAutoresI() == null) {
                        bib.setAutoresI(autemp);
                    } else {
                        bib.addAutor(autemp);
                    }
                    bib.setAutoresF(autemp);
                }
                ntemp = new Nlibro(ltemp);
                if (bib.getLibrosI() == null) {
                    bib.setLibrosI(ntemp);
                } else {
                    Nlibro ultimo = bib.getLibrosF();
                    ultimo.setRl(ntemp);
                }
                autemp.getAutor().addObras(ntemp);
                ltemp.setAutor(autemp.getAutor());
                JOptionPane.showMessageDialog(null, "Libro registrado");
                bib.setLibrosF(ntemp);
            }
        }
        au.setText("");
        libro.setText("");
        gen.setText("");
        cod.setText("");
        libros();
        autores();

    }//GEN-LAST:event_jButton1ActionPerformed
    public void libros() {
        System.out.println("Libros ");
        Nlibro ltemp = bib.getLibrosI();
        while (ltemp != null) {
            System.out.println(ltemp.getLibro().getNombre() + " " + ltemp.getLibro().getISBN());
            ltemp = ltemp.getRl();
        }
        System.out.println("----");
    }

    public void autores() {
        Nautor ltemp = bib.getAutoresI();
        while (ltemp != null) {
            Autor l = ltemp.getAutor();
            System.out.println("Autor");
            System.out.println(l.getNombre());
            System.out.println("-------");
            System.out.println("Obras");
            Nlibro o = l.getObras();
                while (o != null) {
                    System.out.println(o.getLibro().getNombre());
                    o = o.getRl();
                }
                System.out.println("-------");
            ltemp = ltemp.getRl();
        }
        System.out.println("-------");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Five.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Five().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField au;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField libro;
    // End of variables declaration//GEN-END:variables
}
