/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualbiblioteca;

import Models.Nusuario;
import Models.Usuario;
import static biblioteca_departamental.Biblioteca_departamental.bib;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class Second extends javax.swing.JFrame {

    /**
     * Creates new form Second
     */
    public Second() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("C.C.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 80, -1));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 80, -1));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Registro Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconandImagen/12009316-Pila-de-libros-en-una-cubierta-de-color-naranja-sobre-fondo-gris-Foto-de-archivo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 570, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int aux=1;
        String nombre=txt1.getText();
        
        if (isNumeric(nombre)==true) {
            JOptionPane.showMessageDialog(null, "Error  Nombre INCORRECTO");
            aux++;
        }
        if (isNumeric(txt2.getText())==false) {
            JOptionPane.showMessageDialog(null, "Error No Cedula INCORRECTO");
              aux++;
        }
        if (isNumeric(txt3.getText())==false) {
             JOptionPane.showMessageDialog(null, "Error  Telefono INCORRECTO");
               aux++;
        }
        if (aux==1) {
            Nusuario xd=null;
            Usuario temp = new Usuario(Long.parseLong(txt2.getText()),nombre,Long.parseLong(txt3.getText()));
            if(bib.getUsersI()==null){
                Nusuario ntemp=new Nusuario(temp);
                bib.setUsersF(ntemp);
                bib.setUsersI(ntemp);
                JOptionPane.showMessageDialog(null, "Resgistrado");
            }else{
                xd = bib.getUsersI();
                Nusuario ntemp= new Nusuario(temp);
                moverse(xd,ntemp);
            }
        }
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed
    private static void moverse(Nusuario temp,Nusuario add){
        if(temp.getRl()==null ){
            if(temp.getUser().getCc()==add.getUser().getCc()){
            JOptionPane.showMessageDialog(null, "Esta cc ya se utilizo");
            }else if(add.getUser().getCc()<temp.getUser().getCc()){
                add.setRl(temp);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                bib.setUsersI(add);
            }else{
                temp.setRl(add);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                bib.setUsersF(temp);
            }
        }else if(temp.getUser().getCc()==add.getUser().getCc()){
            JOptionPane.showMessageDialog(null, "Esta cc ya se utilizo");
        }else if(add.getUser().getCc()<temp.getUser().getCc()){
                add.setRl(temp);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                bib.setUsersI(add);
        }else{
            moverse(temp.getRl(),add);
        }        
    }
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FirstView vista=new FirstView();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public static boolean isNumeric(String cad){
        return cad != null && cad.matches("[-+]?\\d*\\.?\\d+");  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
